### ISSUE TITLE
I got issue when playing 

### ISSUE THREAD

**Issue by viesurvous** [best-lucky1030/coin-flip#10]
Failed to load resource: the server responded with a status of 500 ()

?

**Comment by viesurvous** [comment]
Status: Something went wrong, please try again.

**Comment by best-lucky1030** [comment]
@viesurvous 
did you try to follow to readme? and already changed and added your secreted key?

**Comment by viesurvous** [comment]
Failed to compile.

./components/Play.tsx:53:24
Type error: Object is of type 'unknown'.

  51 |         const coinFlipData = await program.account.coinFlip.fetch(responseJson.coinFlipPDA);
  52 |
> 53 |         const winner = coinFlipData.state.finished.winner.toString();
     |                        ^
  54 |         if (winner === wallet.publicKey.toString()) setStatusInfo(`You won! Amount: ${betAmount} SOL`);
  55 |         else setStatusInfo(`You lost :(`);
  56 |       } catch (error) {
info  - Checking validity of types .

now i have this and this : 

<img width="770" alt="Capture d’écran 2022-07-27 160828" src="https://user-images.githubusercontent.com/73000712/181268309-b58b8d29-be4f-46a8-bfdf-88353243d83a.png">

**Comment by alphaanon** [comment]
Same error, if you look into node_module you will see there is no Provider context, not sure if npm package for nextjs is working but the node package for react js has the src for the Provider construct I think this is an enviromental issue, still have not been able to find a workaround.

**Comment by best-lucky1030** [comment]
@alphaanon 
yeah, you can try on making environment or to use that package.
Let me check again.

**Comment by best-lucky1030** [comment]
@here
fixed the wallet connection error.
pull the latest code
