### ISSUE TITLE
help pls?

### ISSUE THREAD

**Issue by Tincon1** [best-lucky1030/coin-flip#12]
Hey any chance you can update readME file and show each command to run to get it going?? Would be amazing!

**Comment by best-lucky1030** [comment]
@Tincon1 
thanks for your using this repo.
what kind of commands do you want? those are to deploy rust contracts or run front-end side?

**Comment by Tincon1** [comment]
Commands to deploy contract

**Comment by best-lucky1030** [comment]
you can use this command to deploy contract `anchor build`

**Comment by Tincon1** [comment]
How can I get anchor working properly tho? I installed it and it kept telling me to amv use latest , after I installed it

**Comment by best-lucky1030** [comment]
I think you have to install anchor version `0.22.1`

**Comment by Tincon1** [comment]
I got anchor working, but when I run anchor deploy I get this error

Error: RPC request error: cluster version query failed: error sending request for url (http://localhost:8899/): error trying to connect: tcp connect error: No connection could be made because the target machine actively refused it. (os error 10061)
There was a problem deploying: Output { status: ExitStatus(ExitStatus(1)), stdout: "", stderr: "" }.

**Comment by best-lucky1030** [comment]
seems like it's localhost. change it to devnet.
`solana config set --url https://api.devnet.solana.com`

**Comment by Tincon1** [comment]
Hmmm I now get this

Error: Account Ac9QLf6xvqpupFu64ZuF9PQTrp1bD2hvqxHJi1ib6PUC is not an upgradeable program or already in use
There was a problem deploying: Output { status: ExitStatus(ExitStatus(1)), stdout: "", stderr: "" }.

**Comment by best-lucky1030** [comment]
after remove keygen in deploy, try again.

**Comment by Tincon1** [comment]
Program path: C:\Users\aaa\Desktop\coin-flip\target/deploy/coin_flip.so...
Error: Unable to open program file: The system cannot find the file specified. (os error 2)
There was a problem deploying: Output { status: ExitStatus(ExitStatus(1)), stdout: "", stderr: "" }.

After removing it and redoing anchor deploy it gives me this

**Comment by best-lucky1030** [comment]
Hmm, strange. it worked well on my side.
