### ISSUE TITLE
I got issue when tried to run the app

### ISSUE THREAD

**Issue by chipoel** [best-lucky1030/coin-flip#9]
![image](https://user-images.githubusercontent.com/54360434/179660500-767a3f53-b86c-444e-ba3b-1bf40730c3f3.png)

and how to do this command "Run the app with VENDOR_SECRET_KEY env variable. You can use any keypair as the vendor. Example: VENDOR_SECRET_KEY=[12, 232,1231 ...] npm run dev"

Tried with "VENDOR_SECRET_KEY=[12, 232,1231 ...] npm run dev" ofc i have changed the Vendor Value, but it said "VENDOR_SECRET_KEY COMMAND IS NOT FOUND"

please make a full tutorial about this project :) i'm new at deploying smart contract

**Comment by best-lucky1030** [comment]
@chipoel 
Oh, you have to add your private key(secret key) not like that.
That's just example.
Please try to add yours.

**Comment by best-lucky1030** [comment]
@chipoel
So far there is no response and reply from you.
therefore I think it works for you and will close this issue
